import styles from "../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";

export default function About() {
  return (


    
    <div className={styles.container}>

      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>




        <h1>About </h1>

        <p>
          Sunt id commodo ullamco proident aliqua aliquip aute. Do fugiat
          nostrud excepteur deserunt duis cupidatat ipsum. Culpa ad labore
          labore incididunt minim deserunt pariatur esse magna id laborum
          veniam. Ea mollit amet Lorem aute nulla proident. Quis dolore officia
          sunt aliqua pariatur mollit consequat labore proident proident laborum
          laborum et velit. 
        </p>
      </section>
    </div>
  );
}
