import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Datas from "../data_folder/card.json";
import Link from "next/link";

const Home = () => {
  console.log("Datas");

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="examples" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1>Home page </h1>

        <p>
          Sunt id commodo ullamco proident aliqua aliquip aute. Do fugiat
          nostrud excepteur deserunt duis cupidatat ipsum. Culpa ad labore
          labore incididunt minim deserunt pariatur esse magna id laborum
          veniam. Ea mollit amet Lorem aute nulla proident. Quis dolore officia
          sunt aliqua pariatur mollit consequat labore proident proident laborum
          laborum et velit. Est irure et consectetur et. Aliqua minim sint
          cillum pariatur Lorem ullamco mollit id do. Dolore consectetur do
          voluptate cupidatat. Deserunt eiusmod mollit ullamco magna id. In
          reprehenderit occaecat labore minim amet tempor enim ad duis fugiat
          adipisicing ea anim est. Occaecat do labore labore cupidatat
          reprehenderit nulla exercitation voluptate consequat nulla velit
          deserunt id. Eiusmod aliqua adipisicing laborum enim id sunt amet id
          nostrud pariatur elit officia eiusmod. In ea eu ad laboris occaecat ex
          magna labore amet veniam. Nulla voluptate exercitation dolore ut enim
          deserunt qui nostrud. Enim reprehenderit excepteur do Lorem id
          cupidatat amet. Incididunt adipisicing exercitation nostrud ea ex
          culpa laboris enim exercitation dolor. Ullamco labore voluptate anim
          magna laborum non pariatur reprehenderit adipisicing irure eiusmod
          ullamco. Id officia et deserunt occaecat duis sit dolor irure fugiat
          ad nisi consectetur amet eu. Non consectetur pariatur est duis
          consectetur enim ea aute. Sit nostrud est quis esse consectetur
          cupidatat qui labore excepteur velit. In excepteur voluptate laborum
          commodo ullamco officia adipisicing sint. Non consequat tempor officia
          labore occaecat. Consequat cillum ea enim cupidatat. Irure labore
          magna in in aute enim velit labore eiusmod minim elit sint. Elit sunt
          enim duis ut. Adipisicing occaecat eiusmod qui cupidatat veniam.
          Aliqua pariatur qui dolor nostrud fugiat reprehenderit velit sint sunt
          labore adipisicing commodo consequat. Aliquip aliqua ullamco deserunt
          ex exercitation. Laboris aliquip cupidatat aliqua do nulla duis minim
          commodo aute non adipisicing consequat minim. Sunt irure minim labore
          enim aute. Dolor anim cillum tempor aliqua minim id irure qui ea velit
          amet commodo esse. Quis cillum velit in fugiat et tempor ipsum. Est in
          ex laboris exercitation. Laborum mollit proident et magna proident
          labore cupidatat magna nisi culpa fugiat do in. Anim consequat sint
        </p>

        <div className={styles.d_flex}>
          {Datas &&
            Datas.map((data) => (
              <Link href={"/datas/" + data.id} key={data.id}>
                <a>
                  <div className={styles.container}>
                    <div>
                      <img src={data.images} height={200} width={200} />
                    </div>

                    <h3>{data.moviename}</h3>
                  </div>
                </a>
              </Link>
            ))}
        </div>
      </section>
    </div>
  );
};

export default Home;
